(function () {
  const unit = (id, canDo, pronunciation, reading, dictation, modelAnswer, culture) => ({
    id, canDo, pronunciation, reading, dictation, modelAnswer, culture,
    audio: {
      reading: `audio/a1-${id}-reading.mp3`,
      pronunciation: `audio/a1-${id}-pronunciation.mp3?v=2`,
      pronunciationExamples: pronunciation.examples.map((_, index) => `audio/a1-${id}-pronunciation-${index + 1}.mp3?v=1`),
      dictation: `audio/a1-${id}-dictation.mp3`
    }
  });

  window.A1_MASTERY = {
    units: [
      unit("01",
        ["Μπορώ να συστηθώ με όνομα, χώρα και τόπο κατοικίας.", "Μπορώ να ρωτήσω κάποιον ποιος είναι και από πού έρχεται."],
        { focus: "Το νορβηγικό h και ο καθαρός ρυθμός", tip: "Το h στο hei είναι ένας ελαφρύς αέρας, όχι το ελληνικό χ. Μην τονίζεις όλες τις λέξεις το ίδιο· δώσε βάρος σε όνομα και τόπο.", examples: ["Hei!", "Jeg heter Eleni.", "Jeg bor i Oslo."] },
        { title: "Første dag på kurset", text: "Eleni kommer fra Hellas og bor i Oslo. I dag er hun på norskkurs for første gang. Hun hilser på Jonas og sier: «Hei, jeg heter Eleni. Hyggelig å møte deg!»", questions: [["Πού μένει η Eleni;", ["Στην Αθήνα", "Στο Όσλο", "Στο Μπέργκεν"], 1, "Η φράση «bor i Oslo» δίνει τον τόπο κατοικίας."], ["Γιατί βρίσκεται εκεί;", ["Για δουλειά", "Για καφέ", "Για μάθημα νορβηγικών"], 2, "Το «på norskkurs» σημαίνει σε μάθημα νορβηγικών."]] },
        { text: "Hei, jeg heter Eleni. Jeg kommer fra Hellas, og jeg bor i Oslo.", hint: "Άκου για τις φράσεις jeg heter, kommer fra και bor i." },
        "Hei! Jeg heter Eleni. Jeg kommer fra Hellas, men jeg bor i Oslo. Jeg lærer norsk. Hyggelig å møte deg!",
        "Στη Νορβηγία είναι συνηθισμένο να χρησιμοποιούν γρήγορα το μικρό όνομα, ακόμη και σε πολλές επαγγελματικές καταστάσεις."),
      unit("02",
        ["Μπορώ να καταλάβω και να πω ώρα, ημερομηνία και βασικούς αριθμούς.", "Μπορώ να ρωτήσω πότε αρχίζει ή τελειώνει κάτι."],
        { focus: "Οι αριθμοί tjue και sju", tip: "Στα tjue και sju άκου έναν ήχο κοντά στο ελληνικό σι, αλλά χωρίς να προσθέτεις ξεχωριστό ι. Μάθε τους αριθμούς σε μικρές ομάδες.", examples: ["tjue", "sju", "klokka halv seks"] },
        { title: "En melding om kurset", text: "Norskkurset er på tirsdag 12. september. Det begynner klokka halv seks og slutter klokka åtte. Rommet heter 204. Alex skriver tidspunktet i kalenderen på mobilen.", questions: [["Τι ώρα αρχίζει;", ["17:30", "18:30", "20:00"], 0, "Στα νορβηγικά «halv seks» είναι μισή ώρα πριν από τις έξι: 17:30."], ["Ποιος είναι ο αριθμός της αίθουσας;", ["12", "204", "8"], 1, "Το κείμενο λέει «Rommet heter 204»." ]] },
        { text: "Kurset begynner tirsdag tolvte september klokka halv seks.", hint: "Πρόσεξε ότι halv seks σημαίνει 17:30 και όχι 18:30." },
        "Kurset er på tirsdag. Det begynner klokka halv seks. Jeg kommer ti minutter før. Rommet er nummer 204.",
        "Η νορβηγική ώρα με halv μετρά προς την επόμενη ώρα: halv seks = 5:30."),
      unit("03",
        ["Μπορώ να μιλήσω απλά για την οικογένειά μου.", "Μπορώ να χρησιμοποιήσω βασικές κτητικές λέξεις."],
        { focus: "Ο ήχος kj", tip: "Το kj στο kjære παράγεται με τη γλώσσα ψηλά και τον αέρα μπροστά. Δεν είναι ούτε ελληνικό κ ούτε παχύ σ.", examples: ["kjære", "en kjæreste", "familien min"] },
        { title: "Familien til Sofia", text: "Sofia har en liten familie. Moren hennes bor i Trondheim, og broren hennes studerer i Bergen. Sofia har også en kjæreste. De bor sammen i en leilighet i Oslo.", questions: [["Πού μένει η μητέρα της;", ["Στο Τρόντχαϊμ", "Στο Μπέργκεν", "Στο Όσλο"], 0, "Το «Moren hennes bor i Trondheim» δίνει την απάντηση."], ["Με ποιον μένει η Sofia;", ["Με τον αδελφό της", "Με τον σύντροφό της", "Μόνη"], 1, "Το «De bor sammen» αναφέρεται στη Sofia και στον kjæreste της."]] },
        { text: "Moren min bor i Trondheim, og broren min studerer i Bergen.", hint: "Γράψε moren min και broren min ως δύο ξεχωριστές φράσεις." },
        "Jeg har en søster og en bror. Søsteren min bor i Athen. Broren min studerer. Foreldrene mine bor sammen.",
        "Οι μορφές moren min και min mor είναι και οι δύο σωστές, αλλά η πρώτη είναι πολύ συνηθισμένη στην καθημερινή ομιλία."),
      unit("04",
        ["Μπορώ να περιγράψω μια απλή καθημερινή ρουτίνα.", "Μπορώ να χρησιμοποιήσω συχνά ρήματα στον ενεστώτα."],
        { focus: "Μακρά και βραχέα φωνήεντα", tip: "Ένα φωνήεν πριν από ένα μόνο σύμφωνο είναι συχνά μακρύ. Πριν από διπλό σύμφωνο είναι συνήθως σύντομο. Σύγκρινε tak και takk.", examples: ["tak", "takk", "Jeg spiser frokost."] },
        { title: "En vanlig morgen", text: "Maria står opp klokka halv sju. Hun dusjer og spiser frokost hjemme. Klokka kvart over sju går hun til bussen. Hun begynner på jobb klokka åtte.", questions: [["Τι κάνει πριν πάρει το λεωφορείο;", ["Τρώει πρωινό", "Πηγαίνει στη δουλειά", "Μαγειρεύει βραδινό"], 0, "Πρώτα «spiser frokost», μετά πηγαίνει στη στάση."], ["Τι ώρα αρχίζει δουλειά;", ["06:30", "07:15", "08:00"], 2, "Η τελευταία πρόταση λέει «klokka åtte»." ]] },
        { text: "Jeg står opp klokka halv sju og spiser frokost hjemme.", hint: "Άκου τη σειρά: står opp – klokka – spiser frokost – hjemme." },
        "Jeg står opp klokka sju. Først dusjer jeg. Så spiser jeg frokost. Etterpå tar jeg bussen til jobb.",
        "Το først – så – etterpå βοηθά να οργανώσεις μια σύντομη αφήγηση με φυσικό τρόπο."),
      unit("05",
        ["Μπορώ να παραγγείλω απλό φαγητό και ποτό.", "Μπορώ να ζητήσω τον λογαριασμό και να πληρώσω."],
        { focus: "Το φωνήεν ø", tip: "Για το ø, κράτησε τη γλώσσα όπως στο ελληνικό ε αλλά στρογγύλεψε τα χείλη. Μην το μετατρέπεις σε ο.", examples: ["brød", "melk", "Jeg ønsker en kaffe."] },
        { title: "Lunsj på kafé", text: "Nora går på kafé i lunsjpausen. Hun bestiller en kaffe og et ostesmørbrød. Kaffen koster 38 kroner. Hun betaler med kort og sier takk til servitøren.", questions: [["Τι παραγγέλνει;", ["Τσάι και κέικ", "Καφέ και τοστ με τυρί", "Νερό και σαλάτα"], 1, "Το κείμενο αναφέρει «en kaffe og et ostesmørbrød»."], ["Πώς πληρώνει;", ["Με μετρητά", "Με κινητό", "Με κάρτα"], 2, "Η φράση «betaler med kort» σημαίνει πληρώνει με κάρτα."]] },
        { text: "Jeg vil gjerne ha en kaffe og et ostesmørbrød, takk.", hint: "Η ευγενική φράση είναι vil gjerne ha." },
        "Hei! Jeg vil gjerne ha en kaffe og et ostesmørbrød. Kan jeg få et glass vann også? Jeg betaler med kort, takk.",
        "Το takk χρησιμοποιείται συχνά τόσο όταν ζητάς όσο και όταν λαμβάνεις κάτι."),
      unit("06",
        ["Μπορώ να ζητήσω και να καταλάβω πολύ απλές οδηγίες δρόμου.", "Μπορώ να χρησιμοποιήσω βασικές προθέσεις τοποθεσίας."],
        { focus: "Το νορβηγικό y", tip: "Πες ελληνικό ι κρατώντας τη γλώσσα ψηλά, αλλά στρογγύλεψε τα χείλη σαν να λες ου. Έτσι πλησιάζεις το y.", examples: ["by", "høyre", "sykkel"] },
        { title: "Veien til biblioteket", text: "Biblioteket ligger ved siden av banken. Fra torget går du rett fram til lyskrysset. Der tar du til høyre. Biblioteket er den store bygningen på venstre side.", questions: [["Τι βρίσκεται δίπλα στη βιβλιοθήκη;", ["Η τράπεζα", "Ο σταθμός", "Το σχολείο"], 0, "Ved siden av banken σημαίνει δίπλα στην τράπεζα."], ["Πού στρίβεις στο φανάρι;", ["Αριστερά", "Δεξιά", "Δεν στρίβεις"], 1, "Η οδηγία είναι «tar du til høyre»." ]] },
        { text: "Gå rett fram og ta til høyre ved lyskrysset.", hint: "Δύο προστακτικές: gå και ta." },
        "Unnskyld, hvor er biblioteket? Gå rett fram og ta til høyre. Er det langt? Nei, det tar fem minutter.",
        "Το unnskyld είναι ο φυσικός τρόπος να τραβήξεις ευγενικά την προσοχή κάποιου στον δρόμο."),
      unit("07",
        ["Μπορώ να ρωτήσω τιμή, χρώμα και μέγεθος σε κατάστημα.", "Μπορώ να δείξω ποιο αντικείμενο θέλω."],
        { focus: "Denne, dette και disse", tip: "Μάθε τα ως ρυθμικά σύνολα μαζί με το ουσιαστικό: denne genseren, dette skjørtet, disse skoene.", examples: ["denne genseren", "dette skjørtet", "disse skoene"] },
        { title: "En varm genser", text: "Det er kaldt ute, så Leo trenger en varm genser. Han finner en blå genser i størrelse medium. Den koster 499 kroner. Leo prøver den og kjøper den.", questions: [["Γιατί χρειάζεται πουλόβερ;", ["Επειδή κάνει κρύο", "Επειδή βρέχει", "Επειδή είναι φθηνό"], 0, "Το «Det er kaldt» εξηγεί τον λόγο."], ["Τι μέγεθος αγοράζει;", ["Small", "Medium", "Large"], 1, "Το μέγεθος αναφέρεται ως medium." ]] },
        { text: "Har dere denne genseren i en større størrelse?", hint: "Πρόσεξε τη σειρά Har dere – αντικείμενο – μέγεθος." },
        "Unnskyld, hva koster denne genseren? Har dere den i medium? Kan jeg prøve den? Jeg tar den.",
        "Το «Jeg tar den» είναι ένας φυσικός τρόπος να πεις ότι αποφάσισες να αγοράσεις κάτι."),
      unit("08",
        ["Μπορώ να περιγράψω απλά το σπίτι και ένα δωμάτιο.", "Μπορώ να καταλάβω μια βασική αγγελία κατοικίας."],
        { focus: "Συμφωνικά συμπλέγματα", tip: "Στα stort, skrivebord και kjøkken μην προσθέτεις φωνήεν ανάμεσα στα σύμφωνα. Πες τη λέξη αργά και μετά ως ένα σύνολο.", examples: ["stort rom", "skrivebord", "et kjøkken"] },
        { title: "Et rom til leie", text: "Rommet er lyst og møblert. Det har en seng, et skrivebord og et stort vindu. Leiligheten har felles kjøkken og bad. Husleien er 6 000 kroner i måneden.", questions: [["Τι έχει μέσα το δωμάτιο;", ["Καναπέ και τηλεόραση", "Κρεβάτι και γραφείο", "Μόνο κρεβάτι"], 1, "Αναφέρονται «en seng» και «et skrivebord»."], ["Τι είναι κοινόχρηστο;", ["Η κουζίνα και το μπάνιο", "Το υπνοδωμάτιο", "Το παράθυρο"], 0, "Felles kjøkken og bad σημαίνει κοινόχρηστη κουζίνα και μπάνιο."]] },
        { text: "Leiligheten har et stort kjøkken og et lite bad.", hint: "Άκου τα επίθετα stort και lite πριν από ουδέτερα ουσιαστικά." },
        "Jeg bor i en liten leilighet. Den har ett soverom, et kjøkken og et bad. Stua er lys. Jeg liker hjemmet mitt.",
        "Στις αγγελίες, møblert σημαίνει επιπλωμένο και inkludert σημαίνει ότι κάτι περιλαμβάνεται στην τιμή."),
      unit("09",
        ["Μπορώ να καταλάβω μια απλή πρόγνωση καιρού.", "Μπορώ να επιλέξω και να περιγράψω κατάλληλα ρούχα."],
        { focus: "Τα φωνήεντα å και ø", tip: "Το å είναι πιο ανοιχτό και πίσω, κοντά στο ο. Το ø είναι μπροστινό με στρογγυλά χείλη. Σύγκρινε blå και støvler.", examples: ["blå", "støvler", "Det blåser."] },
        { title: "Været i Bergen", text: "I dag er det ti grader i Bergen. Det regner om morgenen, og det blåser mye. Etter lunsj kommer sola fram. Mina tar på seg regnjakke og støvler.", questions: [["Τι καιρό κάνει το πρωί;", ["Χιονίζει", "Βρέχει", "Έχει ήλιο"], 1, "Το «regner om morgenen» σημαίνει βρέχει το πρωί."], ["Τι φοράει η Mina;", ["Μπουφάν βροχής και μπότες", "Σορτς και σανδάλια", "Παλτό και κασκόλ"], 0, "Παίρνει regnjakke και støvler." ]] },
        { text: "Det regner og blåser, så jeg tar på meg regnjakke.", hint: "Το så συνδέει τον καιρό με την επιλογή ρούχου." },
        "Det er kaldt og det regner i dag. Jeg har på meg en varm genser, regnjakke og støvler. I morgen blir det sol.",
        "Στη Νορβηγία λένε συχνά «Det finnes ikke dårlig vær, bare dårlige klær» — δεν υπάρχει κακός καιρός, μόνο ακατάλληλα ρούχα."),
      unit("10",
        ["Μπορώ να μιλήσω για απλά ενδιαφέροντα και σχέδια.", "Μπορώ να προσκαλέσω κάποιον και να συμφωνήσω ώρα συνάντησης."],
        { focus: "Ο τόνος στις προσκλήσεις", tip: "Σε μια φιλική πρόσκληση η φωνή ανεβαίνει ελαφρά στο τέλος. Δώσε έμφαση στη δραστηριότητα και στην ώρα.", examples: ["Vil du bli med?", "Passer det klokka ti?", "Ja, gjerne!"] },
        { title: "Planer for lørdag", text: "På lørdag skal Emil gå tur ved Sognsvann. Han spør Sara om hun vil bli med. De skal møtes ved T-banen klokka ti. Sara tar med kaffe og matpakke.", questions: [["Πού θα πάνε;", ["Στο μουσείο", "Για πεζοπορία", "Στο κατάστημα"], 1, "Το «gå tur» σημαίνει να πάνε περίπατο ή πεζοπορία."], ["Πού θα συναντηθούν;", ["Στο μετρό", "Στο σπίτι", "Στη λίμνη"], 0, "Το κείμενο λέει «ved T-banen»." ]] },
        { text: "Vil du bli med på tur på lørdag? Vi møtes klokka ti.", hint: "Άκου πρώτα την πρόσκληση και μετά τον χρόνο συνάντησης." },
        "I helgen skal jeg gå på tur. Vil du bli med? Vi kan møtes ved T-banen klokka ti. Jeg tar med kaffe.",
        "Το gå på tur μπορεί να σημαίνει από έναν απλό περίπατο μέχρι πεζοπορία, ανάλογα με τα συμφραζόμενα."),
      unit("11",
        ["Μπορώ να καταλάβω βασικές πληροφορίες σε λεωφορείο.", "Μπορώ να ρωτήσω για στάση, εισιτήριο και καθυστέρηση."],
        { focus: "Συνδεδεμένη ομιλία", tip: "Στη φυσική ομιλία το skal du ακούγεται συχνά σχεδόν σαν ένα σύνολο. Εξάσκησε ολόκληρη τη φράση και όχι γράμμα-γράμμα.", examples: ["Skal du av her?", "Neste stopp", "Bussen er forsinket."] },
        { title: "Bussen er forsinket", text: "Buss 31 til sentrum er ti minutter forsinket. Ida venter på holdeplassen. Hun skal av ved Nationaltheatret og spør sjåføren om bussen stopper der.", questions: [["Πόση είναι η καθυστέρηση;", ["5 λεπτά", "10 λεπτά", "31 λεπτά"], 1, "Η ανακοίνωση λέει «ti minutter forsinket»."], ["Ποιον ρωτά η Ida;", ["Τον οδηγό", "Έναν φίλο", "Τον ελεγκτή"], 0, "Sjåføren είναι ο οδηγός." ]] },
        { text: "Unnskyld, stopper denne bussen ved Nationaltheatret?", hint: "Η ερώτηση αρχίζει με stopper και ακολουθεί το υποκείμενο denne bussen." },
        "Unnskyld, går denne bussen til sentrum? Hvor kjøper jeg billett? Kan du si fra ved neste stopp?",
        "Στα περισσότερα αστικά μέσα το εισιτήριο αγοράζεται πριν από την επιβίβαση μέσω εφαρμογής ή μηχανήματος."),
      unit("12",
        ["Μπορώ να περιγράψω πολύ απλά τη δουλειά και βασικά καθήκοντα.", "Μπορώ να ζητήσω βοήθεια ή να πω τι μπορώ να κάνω."],
        { focus: "Το r και οι ρετροφλεξικοί ήχοι", tip: "Σε πολλές ανατολικές προφορές, r + t/d/n/l συγχωνεύονται. Δεν χρειάζεται να το τελειοποιήσεις τώρα· πρώτα μάθε να το αναγνωρίζεις.", examples: ["arbeid", "fort", "Jeg starter klokka åtte."] },
        { title: "Første dag på jobb", text: "Petros jobber i en butikk. Han starter klokka åtte og fyller varer i hyllene. En kollega viser ham kassa. Petros kan spørre lederen når han trenger hjelp.", questions: [["Πού εργάζεται;", ["Σε κατάστημα", "Σε ξενοδοχείο", "Σε γραφείο"], 0, "Το κείμενο λέει «jobber i en butikk»."], ["Ποιος του δείχνει το ταμείο;", ["Ένας πελάτης", "Ένας συνάδελφος", "Ο αδελφός του"], 1, "En kollega σημαίνει ένας συνάδελφος." ]] },
        { text: "Jeg starter klokka åtte og kan spørre lederen om hjelp.", hint: "Τα modalverb kan ακολουθούνται από απαρέμφατο χωρίς å." },
        "Jeg jobber i en butikk. Jeg starter klokka åtte. Jeg hjelper kunder og fyller varer i hyllene. Jeg kan spørre lederen om hjelp.",
        "Στη νορβηγική εργασιακή κουλτούρα η επικοινωνία είναι συχνά άμεση και η ιεραρχία σχετικά επίπεδη."),
      unit("13",
        ["Μπορώ να καταλάβω απλές οδηγίες μέσα στην τάξη.", "Μπορώ να ζητήσω επανάληψη ή εξήγηση."],
        { focus: "Η μελωδία των ερωτήσεων", tip: "Οι ερωτήσεις με spørreord όπως hva και hvor συχνά κατεβαίνουν στο τέλος. Οι ερωτήσεις ναι/όχι μπορεί να ανεβαίνουν.", examples: ["Hva betyr det?", "Kan du gjenta?", "Hvordan skriver du det?"] },
        { title: "En oppgave på kurset", text: "Læreren skriver tre spørsmål på tavla. Studentene jobber to og to. Nikos forstår ikke det siste spørsmålet, så han ber læreren forklare det én gang til.", questions: [["Πώς εργάζονται οι μαθητές;", ["Μόνοι", "Ανά δύο", "Σε μεγάλη ομάδα"], 1, "To og to σημαίνει ανά δύο."], ["Τι δεν καταλαβαίνει ο Nikos;", ["Την πρώτη λέξη", "Την ώρα", "Την τελευταία ερώτηση"], 2, "Δεν καταλαβαίνει «det siste spørsmålet»." ]] },
        { text: "Beklager, jeg forstår ikke. Kan du forklare det én gang til?", hint: "Χώρισε το σε δύο προτάσεις: δήλωση προβλήματος και ευγενικό αίτημα." },
        "Beklager, hva betyr dette ordet? Kan du gjenta litt saktere? Hvordan skriver man det? Takk for hjelpen.",
        "Το å jobbe to og to και η ενεργή συμμετοχή είναι πολύ συνηθισμένα σε νορβηγικά μαθήματα γλώσσας."),
      unit("14",
        ["Μπορώ να κλείσω, αλλάξω ή ακυρώσω ένα απλό ραντεβού.", "Μπορώ να καταλάβω ημέρα και ώρα ενός ραντεβού."],
        { focus: "Ρυθμός ημερομηνίας και ώρας", tip: "Κάνε μικρή παύση ανάμεσα στην ημέρα, την ημερομηνία και την ώρα. Έτσι μειώνονται τα λάθη κατανόησης.", examples: ["fredag den tolvte", "klokka elleve", "Passer det?"] },
        { title: "En ny time", text: "Kari har en time hos tannlegen torsdag klokka ni. Hun må jobbe da og ringer klinikken. Det er en ledig time fredag klokka elleve, og den passer godt.", questions: [["Γιατί αλλάζει το ραντεβού;", ["Πρέπει να δουλέψει", "Είναι άρρωστη", "Θα ταξιδέψει"], 0, "Το «må jobbe da» εξηγεί τον λόγο."], ["Πότε είναι το νέο ραντεβού;", ["Πέμπτη στις 9", "Παρασκευή στις 11", "Παρασκευή στις 9"], 1, "Η διαθέσιμη ώρα είναι fredag klokka elleve." ]] },
        { text: "Kan jeg flytte timen til fredag klokka elleve?", hint: "Η δομή είναι flytte timen til + νέα ημέρα/ώρα." },
        "Hei, jeg har en time på torsdag, men jeg må jobbe. Kan jeg flytte timen til fredag? Klokka elleve passer fint.",
        "Το en time μπορεί να σημαίνει μία ώρα ή ένα ραντεβού· τα συμφραζόμενα δείχνουν τη σημασία."),
      unit("15",
        ["Μπορώ να περιγράψω πολύ απλά ένα σύμπτωμα.", "Μπορώ να καταλάβω βασικές οδηγίες για φάρμακο ή ξεκούραση."],
        { focus: "Συμπλέγματα στο vondt", tip: "Στο vondt το d δεν ακούγεται καθαρά. Μάθε τη φράση har vondt i ως ένα έτοιμο σύνολο.", examples: ["Jeg har vondt i hodet.", "Jeg er forkjølet.", "Ta det med ro."] },
        { title: "Hos fastlegen", text: "Omar har feber og vondt i halsen. Han bestiller time hos fastlegen. Legen undersøker ham og sier at han skal drikke vann, hvile og ta medisinen to ganger om dagen.", questions: [["Πού πονάει;", ["Στον λαιμό", "Στο πόδι", "Στην πλάτη"], 0, "Vondt i halsen σημαίνει πόνο στον λαιμό."], ["Πόσο συχνά παίρνει το φάρμακο;", ["Μία φορά την εβδομάδα", "Δύο φορές την ημέρα", "Κάθε ώρα"], 1, "Η οδηγία είναι «to ganger om dagen»." ]] },
        { text: "Jeg har feber og vondt i halsen. Jeg trenger en time hos legen.", hint: "Χρησιμοποίησε har για σύμπτωμα και trenger για την ανάγκη." },
        "Hei, jeg har feber og vondt i halsen. Jeg har vært syk i to dager. Kan jeg få en time hos legen?",
        "Ο fastlege είναι ο προσωπικός γενικός γιατρός στο νορβηγικό σύστημα υγείας."),
      unit("16",
        ["Μπορώ να καταλάβω μια πολύ απλή συνταγή.", "Μπορώ να δώσω βασικές οδηγίες μαγειρέματος."],
        { focus: "Καθαρή προστακτική", tip: "Η προστακτική είναι σύντομη και τονισμένη: kutt, bland, stek. Μην προσθέτεις προσωπική αντωνυμία.", examples: ["Kutt løken.", "Bland alt.", "Stek i ti minutter."] },
        { title: "En enkel suppe", text: "Kutt to poteter, én gulrot og en halv løk. Ha grønnsakene i en gryte med vann. Kok i femten minutter. Til slutt tilsetter du litt salt og pepper.", questions: [["Πόσες πατάτες χρειάζονται;", ["Μία", "Δύο", "Τρεις"], 1, "Η συνταγή αρχίζει με «to poteter»."], ["Τι προσθέτεις στο τέλος;", ["Γάλα", "Αλάτι και πιπέρι", "Τυρί"], 1, "Til slutt προσθέτεις salt og pepper." ]] },
        { text: "Kutt grønnsakene og kok dem i femten minutter.", hint: "Δύο προστακτικές: kutt και kok." },
        "Først kutter du grønnsakene. Så har du dem i en gryte med vann. Kok suppen i femten minutter. Tilsett salt til slutt.",
        "Οι νορβηγικές συνταγές χρησιμοποιούν συχνά συντομογραφίες όπως dl, ss και ts."),
      unit("17",
        ["Μπορώ να προσκαλέσω κάποιον στο σπίτι.", "Μπορώ να δεχτώ ή να αρνηθώ ευγενικά μια πρόσκληση."],
        { focus: "Φιλικός και ευγενικός τόνος", tip: "Το gjerne δείχνει θετική διάθεση. Σε άρνηση, χρησιμοποίησε dessverre και δώσε μια σύντομη αιτία.", examples: ["Ja, gjerne!", "Dessverre kan jeg ikke.", "Har du lyst til å komme?"] },
        { title: "Middag hos Ingrid", text: "Ingrid inviterer Kostas på middag fredag kveld. Han kommer klokka sju og tar med blomster. De spiser fisk, snakker norsk og drikker kaffe etter maten.", questions: [["Τι φέρνει ο Kostas;", ["Λουλούδια", "Ψάρι", "Καφέ"], 0, "Το κείμενο λέει «tar med blomster»."], ["Τι κάνουν μετά το φαγητό;", ["Πηγαίνουν βόλτα", "Πίνουν καφέ", "Βλέπουν τηλεόραση"], 1, "Drikker kaffe etter maten σημαίνει πίνουν καφέ μετά το φαγητό." ]] },
        { text: "Har du lyst til å komme på middag på fredag?", hint: "Η πρόσκληση είναι har du lyst til å + απαρέμφατο." },
        "Takk for invitasjonen! Jeg kommer gjerne på fredag. Skal jeg ta med noe? Jeg kan ta med en dessert.",
        "Όταν σε καλούν σπίτι, είναι συνηθισμένο να ρωτήσεις «Skal jeg ta med noe?»"),
      unit("18",
        ["Μπορώ να ξεκινήσω και να τελειώσω μια απλή τηλεφωνική συνομιλία.", "Μπορώ να αφήσω ή να καταλάβω ένα σύντομο μήνυμα."],
        { focus: "Ομαδοποίηση τηλεφωνικού αριθμού", tip: "Οι αριθμοί τηλεφώνου λέγονται σε μικρές ομάδες με σταθερό ρυθμό. Ζήτησε επανάληψη αντί να μαντεύεις.", examples: ["Det er Maria.", "Kan du gjenta nummeret?", "Jeg ringer tilbake."] },
        { title: "En telefon til verkstedet", text: "Andreas ringer et verksted, men mekanikeren er opptatt. Han sier navnet og telefonnummeret sitt. Mekanikeren skal ringe tilbake etter klokka tre.", questions: [["Γιατί δεν μιλά με τον μηχανικό;", ["Ο μηχανικός λείπει", "Ο μηχανικός είναι απασχολημένος", "Έχει λάθος αριθμό"], 1, "Opptatt σημαίνει απασχολημένος."], ["Πότε θα τον καλέσουν;", ["Πριν τις τρεις", "Στις δύο", "Μετά τις τρεις"], 2, "Η φράση είναι «etter klokka tre»." ]] },
        { text: "Hei, det er Andreas. Kan du ringe meg tilbake etter klokka tre?", hint: "Στο τηλέφωνο συστήνεσαι με det er + όνομα." },
        "Hei, det er Andreas. Jeg ringer om bilen min. Kan du ringe meg tilbake? Nummeret mitt er 98 12 34 56.",
        "Στα νορβηγικά συστήνεσαι συχνά στο τηλέφωνο με «Det er …» και όχι με «Jeg er …»."),
      unit("19",
        ["Μπορώ να ζητήσω μια βασική υπηρεσία σε ταχυδρομείο ή τράπεζα.", "Μπορώ να καταλάβω απλές πληροφορίες για τιμή και ταυτοποίηση."],
        { focus: "Καθαροί μεγάλοι αριθμοί", tip: "Χώρισε εκατοντάδες και δεκάδες με μικρή παύση. Έλεγξε τον αριθμό επαναλαμβάνοντάς τον.", examples: ["hundre kroner", "et kontonummer", "Kan du gjenta beløpet?"] },
        { title: "En pakke til Hellas", text: "Dimitra skal sende en pakke til Thessaloniki. På posten viser hun legitimasjon og skriver adressen tydelig. Pakken veier to kilo og koster 245 kroner å sende.", questions: [["Τι δείχνει στο ταχυδρομείο;", ["Εισιτήριο", "Ταυτότητα", "Τραπεζική κάρτα"], 1, "Legitimasjon είναι αποδεικτικό ταυτότητας."], ["Πόσο ζυγίζει το δέμα;", ["2 κιλά", "245 κιλά", "20 κιλά"], 0, "Το κείμενο λέει «veier to kilo»." ]] },
        { text: "Jeg vil gjerne sende denne pakken til Hellas.", hint: "Η ευγενική δομή vil gjerne επανέρχεται και στις υπηρεσίες." },
        "Hei, jeg vil gjerne sende denne pakken til Hellas. Hvor mye koster det? Når kommer pakken fram? Her er legitimasjonen min.",
        "Πολλές ταχυδρομικές υπηρεσίες στη Νορβηγία λειτουργούν μέσα σε καταστήματα τροφίμων ως Post i Butikk."),
      unit("20",
        ["Μπορώ να αγοράσω εισιτήριο και να καταλάβω βασικές ταξιδιωτικές πληροφορίες.", "Μπορώ να ρωτήσω για αναχώρηση, αποβάθρα και αλλαγή."],
        { focus: "Νορβηγικά τοπωνύμια", tip: "Μην εφαρμόζεις αυτόματα ελληνικούς κανόνες ανάγνωσης. Άκου και επανάλαβε ολόκληρα τα ονόματα Bergen, Trondheim και Stavanger.", examples: ["Bergen", "Trondheim", "Hvilket spor?"] },
        { title: "Toget til Bergen", text: "Toget til Bergen går klokka 08.25 fra spor 4. Anna har billetten på mobilen. Hun må bytte tog på Voss, og hun kommer fram til Bergen om ettermiddagen.", questions: [["Από ποια αποβάθρα φεύγει;", ["2", "4", "8"], 1, "Spor 4 είναι η αποβάθρα 4."], ["Πού αλλάζει τρένο;", ["Στο Όσλο", "Στο Voss", "Στο Μπέργκεν"], 1, "Η πρόταση λέει «bytte tog på Voss»." ]] },
        { text: "Når går toget til Bergen, og hvilket spor går det fra?", hint: "Δύο ερωτήσεις ενώνονται με og." },
        "Jeg vil gjerne ha en billett til Bergen. Når går toget? Hvilket spor går det fra? Må jeg bytte tog?",
        "Το spor χρησιμοποιείται για σιδηροδρομική γραμμή ή αποβάθρα, ενώ το holdeplass για στάση λεωφορείου ή τραμ."),
      unit("21",
        ["Μπορώ να πω με απλές προτάσεις τι έκανα χθες.", "Μπορώ να καταλάβω μια σύντομη αφήγηση στο παρελθόν."],
        { focus: "Καταλήξεις παρελθοντικού", tip: "Άκου τις καταλήξεις -et, -te και -de χωρίς να τις υπερτονίζεις. Μάθε συχνά ανώμαλα ρήματα ως ολόκληρες μορφές.", examples: ["jobbet", "kjøpte", "bodde"] },
        { title: "En travel mandag", text: "I går sto Lina opp tidlig. Hun tok bussen til jobb og jobbet til klokka fire. Etter jobb handlet hun mat og laget middag. Om kvelden så hun en serie.", questions: [["Τι έκανε μετά τη δουλειά;", ["Αγόρασε τρόφιμα", "Πήγε για τρέξιμο", "Κοιμήθηκε"], 0, "Handlet mat σημαίνει αγόρασε τρόφιμα."], ["Τι είδε το βράδυ;", ["Μια ταινία", "Μια σειρά", "Ειδήσεις"], 1, "Η τελευταία πρόταση λέει «så hun en serie»." ]] },
        { text: "I går tok jeg bussen til jobb og laget middag hjemme.", hint: "Πρόσεξε τα ανώμαλα tok και τα ομαλά laget." },
        "I går sto jeg opp klokka sju. Jeg tok bussen til jobb. Etter jobb handlet jeg mat og laget middag. Om kvelden var jeg hjemme.",
        "Το i går τοποθετεί καθαρά την αφήγηση στο παρελθόν και συχνά έρχεται πρώτο για να οργανώσει την πρόταση."),
      unit("22",
        ["Μπορώ να πω τι σκοπεύω ή θέλω να κάνω.", "Μπορώ να κάνω ένα απλό σχέδιο με άλλο άτομο."],
        { focus: "Η φυσική προφορά του skal", tip: "Στην καθημερινή ομιλία το skal συχνά είναι σύντομο και άτονο. Μην το προφέρεις βαρύτερα από το κύριο ρήμα.", examples: ["Jeg skal jobbe.", "Vi skal møtes.", "Hva vil du gjøre?"] },
        { title: "Neste uke", text: "Neste uke skal Yannis begynne på et nytt kurs. Han vil øve norsk hver dag. På onsdag skal han møte en språkvenn, og i helgen vil han besøke familien.", questions: [["Τι αρχίζει την επόμενη εβδομάδα;", ["Νέα δουλειά", "Νέο μάθημα", "Νέο βιβλίο"], 1, "Η πρώτη πρόταση λέει «et nytt kurs»."], ["Πότε συναντά φίλο γλώσσας;", ["Τετάρτη", "Παρασκευή", "Σαββατοκύριακο"], 0, "På onsdag σημαίνει την Τετάρτη." ]] },
        { text: "Neste uke skal jeg begynne på kurs og øve norsk hver dag.", hint: "Το skal δείχνει συγκεκριμένο σχέδιο." },
        "Neste uke skal jeg jobbe mandag og tirsdag. På onsdag skal jeg møte en venn. I helgen vil jeg slappe av og gå på tur.",
        "Το skal εκφράζει συχνά οργανωμένο σχέδιο, ενώ το vil μπορεί να εκφράζει επιθυμία ή πρόθεση."),
      unit("23",
        ["Μπορώ να πω τι μου αρέσει και τι προτιμώ.", "Μπορώ να κάνω μια πολύ απλή σύγκριση."],
        { focus: "Έμφαση στη σύγκριση", tip: "Στις συγκρίσεις τόνισε τις λέξεις bedre, mer και enn. Αυτό κάνει τη διαφορά πιο εύκολη να ακουστεί.", examples: ["Jeg liker kaffe bedre.", "Te er billigere enn kaffe.", "Hva liker du best?"] },
        { title: "Kaffe eller te?", text: "Ane liker både kaffe og te, men hun liker kaffe best om morgenen. På kvelden drikker hun heller te. Kaffe er sterkere, mens te er roligere for henne.", questions: [["Τι προτιμά το πρωί;", ["Καφέ", "Τσάι", "Νερό"], 0, "Liker kaffe best om morgenen σημαίνει προτιμά καφέ το πρωί."], ["Πότε πίνει τσάι;", ["Το πρωί", "Στη δουλειά", "Το βράδυ"], 2, "På kvelden σημαίνει το βράδυ." ]] },
        { text: "Jeg liker kaffe bedre enn te, men te er billigere.", hint: "Η σύγκριση σχηματίζεται με συγκριτικό + enn." },
        "Jeg liker både byen og naturen. Byen er mer praktisk, men naturen er roligere. Jeg liker naturen best i helgen.",
        "Το både … og σημαίνει και το ένα και το άλλο, ενώ το heller δείχνει προτίμηση."),
      unit("24",
        ["Μπορώ να εξηγήσω ένα μικρό καθημερινό πρόβλημα.", "Μπορώ να ζητήσω βοήθεια και να καταλάβω μια απλή λύση."],
        { focus: "Η θέση και η έμφαση του ikke", tip: "Το ikke συνήθως έρχεται μετά το κλιτό ρήμα σε κύρια πρόταση. Τόνισέ το όταν διορθώνεις ή αρνείσαι κάτι.", examples: ["Kortet virker ikke.", "Jeg finner ikke nøkkelen.", "Bussen kommer ikke."] },
        { title: "Kortet virker ikke", text: "Mina står i butikken, men bankkortet virker ikke. Hun prøver én gang til uten hell. Hun betaler med mobilen og ringer banken etterpå for å spørre hva som er galt.", questions: [["Ποιο είναι το πρόβλημα;", ["Δεν έχει χρήματα", "Δεν λειτουργεί η κάρτα", "Έχασε το κινητό"], 1, "Η φράση «bankkortet virker ikke» περιγράφει το πρόβλημα."], ["Πώς πληρώνει τελικά;", ["Με το κινητό", "Με μετρητά", "Δεν πληρώνει"], 0, "Η λύση είναι «betaler med mobilen»." ]] },
        { text: "Bankkortet mitt virker ikke. Kan du hjelpe meg?", hint: "Πρώτα περιγράφεις το πρόβλημα και μετά ζητάς βοήθεια." },
        "Unnskyld, kortet mitt virker ikke. Jeg har prøvd to ganger. Kan jeg betale med mobilen? Takk for hjelpen.",
        "Μια σαφής δομή πρόβλημα → αίτημα → επιβεβαίωση λειτουργεί καλά σε πολλές καθημερινές καταστάσεις."),
      unit("25",
        ["Μπορώ να δώσω πολύ απλές πληροφορίες για τόπους στη Νορβηγία.", "Μπορώ να περιγράψω πού βρίσκεται ένας τόπος και τι μπορείς να κάνεις εκεί."],
        { focus: "Ρυθμός στον πληθυντικό", tip: "Οι καταλήξεις -er και -ene είναι συνήθως άτονες. Κράτησε το βάρος στη ρίζα της λέξης.", examples: ["fjorder", "byene", "fjellene"] },
        { title: "Tre steder i Norge", text: "Oslo ligger på Østlandet og er den største byen i Norge. Bergen ligger på Vestlandet og er kjent for regn og fjorder. Tromsø ligger i Nord-Norge, og om vinteren kan du se nordlyset der.", questions: [["Ποια πόλη είναι γνωστή για τα φιόρδ;", ["Όσλο", "Μπέργκεν", "Τρόμσο"], 1, "Η πρόταση για το Bergen αναφέρει regn og fjorder."], ["Πού μπορείς να δεις βόρειο σέλας;", ["Στο Tromsø", "Στο Oslo", "Στο Bergen"], 0, "Το nordlyset συνδέεται στο κείμενο με το Tromsø." ]] },
        { text: "Bergen ligger på Vestlandet og er kjent for fjordene.", hint: "Άκου την οριστική πληθυντικού fjordene." },
        "Jeg vil besøke Bergen. Byen ligger på Vestlandet. Den er kjent for fjordene og de gamle husene. Jeg vil ta toget dit.",
        "Οι ονομασίες Østlandet, Vestlandet, Sørlandet, Trøndelag και Nord-Norge χρησιμοποιούνται συχνά για μεγάλες περιοχές."),
      unit("26",
        ["Μπορώ να πω πολύ απλά ότι κάτι έχει συμβεί.", "Μπορώ να καταλάβω βασικές ερωτήσεις για ένα πρόσφατο γεγονός."],
        { focus: "Το perfektum ως ρυθμικό σύνολο", tip: "Πες har + μετοχή χωρίς μεγάλη παύση. Το har είναι συχνά άτονο και η σημαντική πληροφορία βρίσκεται στη μετοχή.", examples: ["Jeg har mistet nøkkelen.", "Bussen har kommet.", "Hva har skjedd?"] },
        { title: "Nøkkelen er borte", text: "Eva har mistet nøkkelen til leiligheten. Hun har lett i veska og i jakkelommene, men finner den ikke. Hun ringer naboen, som har en ekstra nøkkel.", questions: [["Τι έχασε;", ["Την τσάντα", "Το κλειδί", "Το μπουφάν"], 1, "Har mistet nøkkelen σημαίνει έχει χάσει το κλειδί."], ["Ποιος έχει δεύτερο κλειδί;", ["Ο γείτονας", "Ο ιδιοκτήτης", "Ο φίλος"], 0, "Η τελευταία πρόταση αναφέρει naboen." ]] },
        { text: "Jeg har mistet nøkkelen og har lett overalt.", hint: "Και τα δύο ρήματα χρησιμοποιούν har + μετοχή." },
        "Jeg har mistet nøkkelen min. Jeg har sett i veska og i lommene. Kan jeg låne ekstranøkkelen?",
        "Το perfektum είναι χρήσιμο όταν ένα πρόσφατο γεγονός έχει αποτέλεσμα τώρα: το κλειδί χάθηκε και ακόμη λείπει."),
      unit("27",
        ["Μπορώ να καταλάβω και να γράψω ένα πολύ απλό ψηφιακό μήνυμα.", "Μπορώ να ζητήσω βοήθεια για μια εφαρμογή ή σύνδεση."],
        { focus: "Ψηφιακές δάνειες λέξεις", tip: "Πολλές λέξεις μοιάζουν με αγγλικά, αλλά ακολουθούν νορβηγικό ρυθμό. Άκου ολόκληρη τη φράση αντί να τις προφέρεις αγγλικά.", examples: ["en app", "en e-post", "Jeg logger inn."] },
        { title: "En melding i appen", text: "Mats får en melding fra norskkurset i appen. Læreren har lagt ut en ny oppgave. Mats åpner lenken, men han husker ikke passordet og må lage et nytt.", questions: [["Από ποιον είναι το μήνυμα;", ["Από την τράπεζα", "Από το μάθημα νορβηγικών", "Από τον γιατρό"], 1, "Το μήνυμα είναι «fra norskkurset»."], ["Ποιο είναι το πρόβλημα;", ["Δεν θυμάται τον κωδικό", "Δεν έχει κινητό", "Δεν βρίσκει την εφαρμογή"], 0, "Husker ikke passordet σημαίνει δεν θυμάται τον κωδικό." ]] },
        { text: "Jeg husker ikke passordet og må lage et nytt.", hint: "Η άρνηση έρχεται μετά το husker και το må δείχνει ανάγκη." },
        "Hei! Jeg finner ikke oppgaven i appen. Kan du sende lenken på nytt? Takk for hjelpen!",
        "Πριν από προσωπικές πληροφορίες, έλεγξε πάντα ποιος έστειλε έναν σύνδεσμο και μην κοινοποιείς κωδικούς."),
      unit("28",
        ["Μπορώ να περιγράψω απλά τη γειτονιά μου.", "Μπορώ να ζητήσω συγγνώμη και να προτείνω μια απλή λύση σε γείτονα."],
        { focus: "Η μελωδία της συγγνώμης", tip: "Στο beklager χαμήλωσε ελαφρά τον τόνο και μίλα ήρεμα. Η λύση που ακολουθεί πρέπει να ακούγεται καθαρά.", examples: ["Beklager at det bråker.", "Jeg skal skru ned musikken.", "Takk for at du sier fra."] },
        { title: "Musikk i leiligheten", text: "Det er sent, og musikken hos Daniel er høy. Naboen banker på døra og sier at barnet hennes sover. Daniel beklager og skrur ned musikken med en gang.", questions: [["Γιατί έρχεται η γειτόνισσα;", ["Θέλει καφέ", "Η μουσική είναι δυνατή", "Έχασε το κλειδί"], 1, "Η αιτία είναι ότι «musikken … er høy»."], ["Τι κάνει ο Daniel;", ["Κλείνει την πόρτα", "Χαμηλώνει τη μουσική", "Φεύγει"], 1, "Skrur ned musikken σημαίνει χαμηλώνει τη μουσική." ]] },
        { text: "Beklager at det bråker. Jeg skal skru ned musikken med en gang.", hint: "Η συγγνώμη ακολουθείται από at + πρόταση και μετά από λύση." },
        "Beklager at det bråker. Jeg visste ikke at musikken var så høy. Jeg skal skru den ned med en gang.",
        "Το «Takk for at du sier fra» δείχνει ότι δέχεσαι μια παρατήρηση χωρίς σύγκρουση."),
      unit("29",
        ["Μπορώ να συνδέσω απλές προτάσεις για να περιγράψω μια ημέρα.", "Μπορώ να χρησιμοποιήσω βασικούς χρονικούς συνδέσμους."],
        { focus: "Ρυθμός με χρονικούς συνδέσμους", tip: "Κάνε ελαφρά παύση μετά από først, så, etterpå και til slutt. Έτσι η αφήγηση γίνεται κατανοητή.", examples: ["Først spiser jeg frokost.", "Så går jeg på jobb.", "Til slutt drar jeg hjem."] },
        { title: "En hel dag", text: "Først leverer Maria sønnen i barnehagen. Så tar hun toget til jobb. Etter jobb handler hun og lager middag. Til slutt leser hun litt norsk før hun legger seg.", questions: [["Τι κάνει πρώτο;", ["Πηγαίνει στη δουλειά", "Αφήνει τον γιο της στον παιδικό σταθμό", "Μαγειρεύει"], 1, "Først εισάγει την πρώτη ενέργεια."], ["Πότε διαβάζει νορβηγικά;", ["Πριν κοιμηθεί", "Στο τρένο", "Το πρωί"], 0, "Διαβάζει «før hun legger seg»." ]] },
        { text: "Etter jobb handler jeg, og så lager jeg middag hjemme.", hint: "Χρησιμοποίησε etter και så για να κρατήσεις τη σωστή σειρά." },
        "Først står jeg opp og spiser frokost. Så drar jeg på jobb. Etter jobb handler jeg. Til slutt lager jeg middag og slapper av.",
        "Οι χρονικοί σύνδεσμοι κάνουν ακόμη και πολύ απλές προτάσεις να ακούγονται σαν ολοκληρωμένη αφήγηση."),
      unit("30",
        ["Μπορώ να παρουσιάσω τον εαυτό μου και την καθημερινότητά μου με απλές συνδεδεμένες προτάσεις.", "Μπορώ να διαχειριστώ βασικές συναλλαγές και πολύ απλές συνομιλίες με υποστήριξη."],
        { focus: "Έτοιμα γλωσσικά σύνολα", tip: "Η ευχέρεια στο A1 έρχεται από φράσεις που έχεις εξασκήσει ως σύνολα. Κράτησε σταθερό ρυθμό και μην σταματάς σε κάθε λέξη.", examples: ["Jeg heter … og kommer fra …", "Til vanlig jobber jeg …", "På fritiden liker jeg å …"] },
        { title: "Nå kan jeg mer", text: "For tre måneder siden kunne Eleni nesten ikke norsk. Nå kan hun presentere seg, handle, bestille mat og spørre om veien. Hun forstår enkle meldinger og tør å snakke med naboene. Neste mål er A2.", questions: [["Τι μπορούσε να κάνει πριν τρεις μήνες;", ["Μιλούσε άπταιστα", "Σχεδόν καθόλου νορβηγικά", "Δούλευε ως δασκάλα"], 1, "Kunne nesten ikke norsk σημαίνει ότι ήξερε ελάχιστα."], ["Ποιος είναι ο επόμενος στόχος;", ["B1", "A2", "C1"], 1, "Η τελευταία πρόταση λέει «Neste mål er A2»." ]] },
        { text: "Nå kan jeg presentere meg, handle og spørre om veien på norsk.", hint: "Το kan μοιράζεται τρία απαρέμφατα χωρίς å." },
        "Hei! Jeg heter Eleni og kommer fra Hellas. Nå bor jeg i Oslo og lærer norsk. Til vanlig jobber jeg på et hotell. På fritiden liker jeg å gå tur og møte venner. Neste mål er A2.",
        "Το A1 δεν σημαίνει τελειότητα· σημαίνει ότι μπορείς να ενεργήσεις σε πολύ απλές, γνώριμες καταστάσεις με έναν υποστηρικτικό συνομιλητή.")
    ],
    checkpoints: {
      "05": { title: "Oppdrag 1 · Første møte", scenario: "Συστήσου σε έναν νέο γνωστό και παραγγείλετε μαζί σε καφέ.", tasks: ["Άκου μια σύντομη γνωριμία χωρίς να κοιτάξεις το κείμενο.", "Διάβασε ώρα και τιμές από έναν μικρό κατάλογο.", "Ηχογράφησε παρουσίαση 30–45 δευτερολέπτων.", "Γράψε 4 προτάσεις για εσένα και μία παραγγελία."] },
      "10": { title: "Oppdrag 2 · En lørdag i byen", scenario: "Βρες ένα μέρος, αγόρασε κάτι και κανόνισε δραστηριότητα για το Σάββατο.", tasks: ["Ακολούθησε τρεις απλές οδηγίες δρόμου.", "Διάβασε μια αγγελία και μια πρόγνωση καιρού.", "Ηχογράφησε πρόσκληση με τόπο και ώρα.", "Γράψε τι θα φορέσεις και τι θα κάνεις."] },
      "15": { title: "Oppdrag 3 · Hverdag og hjelp", scenario: "Μετακινήσου, επικοινώνησε στη δουλειά και άλλαξε ένα ραντεβού.", tasks: ["Άκου ανακοίνωση μεταφοράς και εντόπισε στάση και καθυστέρηση.", "Διάβασε ένα μήνυμα από εργασία ή μάθημα.", "Ηχογράφησε τηλεφώνημα για αλλαγή ραντεβού.", "Γράψε δύο συμπτώματα και ζήτησε ραντεβού γιατρού."] },
      "20": { title: "Oppdrag 4 · Praktisk norsk", scenario: "Οργάνωσε δείπνο, τηλεφώνησε, στείλε δέμα και αγόρασε εισιτήριο.", tasks: ["Άκου μια πρόσκληση και απάντησε κατάλληλα.", "Διάβασε συνταγή και ταξιδιωτικό πίνακα.", "Ηχογράφησε σύντομο τηλεφωνικό μήνυμα.", "Γράψε τις βασικές πληροφορίες ενός ταξιδιού."] },
      "25": { title: "Oppdrag 5 · Fortid og framtid", scenario: "Πες τι έγινε, τι θα κάνεις και ποιο μέρος της Νορβηγίας προτιμάς.", tasks: ["Ξεχώρισε παρελθόν και μέλλον σε σύντομες φράσεις.", "Διάβασε πληροφορίες για τρεις νορβηγικές πόλεις.", "Ηχογράφησε τι έκανες χθες και τι θα κάνεις αύριο.", "Γράψε μια απλή σύγκριση δύο τόπων."] },
      "30": { title: "A1-sluttoppdrag · Mitt liv på norsk", scenario: "Ολοκλήρωσε μια μικρή προσομοίωση των τεσσάρων δεξιοτήτων και παρουσίασε τη ζωή σου.", tasks: ["Άκου δύο καθημερινά μηνύματα και βρες τις βασικές πληροφορίες.", "Διάβασε πινακίδα, μήνυμα, πρόγραμμα και σύντομη ιστορία.", "Ηχογράφησε παρουσίαση 60 δευτερολέπτων και απάντησε σε τρεις ερωτήσεις.", "Γράψε 6–8 συνδεδεμένες προτάσεις για εσένα, τη ρουτίνα και τα σχέδιά σου."] }
    }
  };
})();
